name: PR Unit Tests

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Run Backend Unit Tests
        run: dotnet test ./TodoApi.Tests --filter FullyQualifiedName~UnitTests --no-build --verbosity normal

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Run Frontend Unit Tests
        run: |
          cd todo_spa
          yarn install
          yarn test:unit
